### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BrProc** [SSKirillSS/rac-compat#2]
[13:08:54] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'double it.hurts.sskirillss.relics.utils.WorldUtils.getGroundHeight(net.minecraft.world.entity.Entity, net.minecraft.world.phys.Vec3, int)'
	at it.hurts.sskirillss.raccompat.items.PolarBootItem.getGroundDistance(PolarBootItem.java:227) ~[raccompat-1.20.1-0.1.3.jar%23476!/:1.20.1-0.1.3]
	at it.hurts.sskirillss.raccompat.items.PolarBootItem.onEntityItemUpdate(PolarBootItem.java:206) ~[raccompat-1.20.1-0.1.3.jar%23476!/:1.20.1-0.1.3]
	at net.minecraftforge.common.extensions.IForgeItemStack.onEntityItemUpdate(IForgeItemStack.java:280) ~[forge-1.20.1-47.3.0-universal.jar%23527!/:?]
	at net.minecraft.world.entity.item.ItemEntity.m_8119_(ItemEntity.java:103) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23522!/:?]
	... 5 more

**Comment by SSKirillSS** [comment]
Looks like you have an outdated version of something. Check updates for Relics, OctoLib and RAC-Compat.

**Comment by BrProc** [comment]
Okay, sorry, I forgot to check for updates of other dependencies.
